version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
  rebase-strategy: "disabled"
  open-pull-requests-limit: 99
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  groups:
    dependencies:
      applies-to: version-updates
      dependency-type: "production"
  ignore:
  # Newer versions break on our email contents (see #5017)
  - dependency-name: html2text
    versions:
    - "> 2020.1.16"
  # We're just not interested in messing around with updates to this module
  # (changes to its capitalisation rules break our tests)
  - dependency-name: titlecase
    versions:
    - "> 0.12.0"
  # Version 4.2 is the latest Django LTS version, we want patch updates to that
  # but no major version updates until we manually upgrade to the next LTS
  - dependency-name: django
    versions:
    - ">= 4.3"
