version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  rebase-strategy: "disabled"
  open-pull-requests-limit: 5
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  ignore:
  # We're just not interested in messing around with updates to this module
  # (changes to its capitalisation rules break our tests)
  - dependency-name: titlecase
    versions:
    - "> 0.12.0"
  - dependency-name: django
    versions:
    - ">= 3.0"
