---
engines:
  pep8:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    exclude_fingerprints:
      - e4038bcde35df907de39f459b4bd8754
      - 6a53cebf909a90ce152c95b3916b4ec6
    config:
      languages:
        python:
          mass_threshold: 70
        javascript:
  eslint:
    enabled: true
    channel: "eslint-2"
  fixme:
    enabled: true
  radon:
    enabled: true
    checks:
      Complexity:
        enabled: false
ratings:
  paths:
  - "**.css"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths:
 - "**/vendor/"
 - "openprescribing/media/css/*bootstrap.css"
 - "openprescribing/static/rest_framework*"
 - "openprescribing/static/js/"
 - "openprescribing/static/css/"
 - "openprescribing/media/js/*.js"
 - "openprescribing/frontend/migrations/*"
 - "openprescribing/openprescribing/settings/*"
 - "openprescribing/frontend/management/commands/grab_chart.js"
