---
version: 2
checks:
  argument-count:
    config:
      threshold: 6
  complex-logic:
    config:
      threshold: 4
  file-lines:
    config:
      threshold: 450
  method-complexity:
    config:
      threshold: 6
  method-count:
    config:
      threshold: 20
  method-lines:
    config:
      threshold: 60
  nested-control-flow:
    config:
      threshold: 4
  return-statements:
    config:
      threshold: 4
  similar-code:
    config:
      threshold: # language-specific defaults. an override will affect all languages.
  identical-code:
    config:
      threshold: # language-specific defaults. an override will affect all languages
engines:
  pep8:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    exclude_fingerprints:
      - e4038bcde35df907de39f459b4bd8754
      - 6a53cebf909a90ce152c95b3916b4ec6
    config:
      languages:
        python:
          mass_threshold: 70
        javascript:
  eslint:
    enabled: true
    channel: "eslint-4"
    config:
      config: .eslintrc
  fixme:
    enabled: true
  radon:
    enabled: true
    checks:
      Complexity:
        enabled: false
ratings:
  paths:
  - "**.css"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths:
 - "**/vendor/"
 - "openprescribing/media/css/*bootstrap.css"
 - "openprescribing/static/rest_framework*"
 - "openprescribing/static/js/"
 - "openprescribing/static/css/"
 - "openprescribing/media/js/*.js"
 - "openprescribing/frontend/migrations/*"
 - "openprescribing/openprescribing/settings/*"
 - "openprescribing/frontend/management/commands/grab_chart.js"
checks:
  argument-count:
    enabled: false
  complex-logic:
    enabled: false
  file-lines:
    enabled: false
  method-complexity:
    enabled: false
  method-count:
    enabled: false
  method-lines:
    enabled: false
  nested-control-flow:
    enabled: false
  return-statements:
    enabled: false
  similar-code:
    enabled: false
  identical-code:
    enabled: false
