sudo: required
matrix:
  include:
    - name: "Unit tests"
      script: docker-compose run --service-ports test && docker-compose run --service-ports test-production
      env: TEST_SUITE=nonfunctional
    - name: "Functional tests"
      script: docker-compose run --service-ports test && docker-compose run --service-ports test-production
      env: TEST_SUITE=functional BROWSER="internet explorer:11.0:Windows 7"
    - name: "Ansible buildout test"
      script:
        - docker run -v ${TRAVIS_BUILD_DIR}:/openprescribing/ dockette/stretch /bin/bash -c "cd /openprescribing/ansible && bash test_playbook.sh"
      env: LANG=en_US.UTF-8
    - name: "Linting"
      script:
        - pip install black==19.3b0
        - pip install flake8==3.7.8
        - scripts/lint.sh
  allow_failures:
    # There is currently some kind of issue with our Saucelabs set up
    # (presumably something has upgraded somewhere and introduced an
    # incompatibility) so the functional tests no longer run, though they all
    # still pass locally. As we don't have time to debug this now I'm setting
    # these back to "allowed failures". At the point when we start doing
    # significant work on OP again we can try to solve this properly.
    - env: TEST_SUITE=functional BROWSER="internet explorer:11.0:Windows 7"
cache:
  directories:
    docker
services:
  docker
language: python
python:
  # The application runs against 3.5, which is set in the Dockerfile that is used to
  # create the docker image that runs the tests.  This Python version is used for
  # running the Travis jobs.  3.6 is required to run black in lint.sh.
  - "3.6"
before_install:
  - openssl aes-256-cbc -K $encrypted_c3e391f06205_key -iv $encrypted_c3e391f06205_iv -in google-credentials-ebmdatalabtest-1ad80daf5cc1.json.enc -out google-credentials.json -d
install:
  - docker pull dockette/stretch
  - docker pull ebmdatalab/openprescribing-base:latest
  - docker pull mdillon/postgis:11
before_script:
  - export SAUCE_HOST=$(ip -4 addr show scope global dev docker0 | grep inet | awk '{print $2}' | cut -d / -f 1)
notifications:
  email:
    - tech@ebmdatalab.net
  slack:
    secure: ECNcYBYWt4emYm9Br88Ts9VRxHGe3IkMjLk/MTKAaqY3lJPmC7vy+d1+YazBufxPNAIbR/1OdxJGcxsnj+zpYoCgLVOF9sxWaOf6x9dL2bTquU+lUIzUVDb+VilRgnlqv9BHZQlcYUFsODQTqQhxeJ73pUpVxYsdXWuSs5CGgJMsJMJ6IQAgiLBStC/8dNCXFFQPGptjdA1xqeCG47lnLK0zwzlaWJobrqga50NqlL4xfjMnVXq+AohGq5HtmrOt4cy6HkX3zKuHR0GZs6j/hWA6wbIbGeO5d/4hGT0CaiROlK1trketyvec8z69MqjsQJrK0Au1KYF7VOhJjLykseFiTK4IdluLipn3rVX9JRjBAegrrMEy/Cpjgc8nJqo3WAYoaPL7SY+jl8vwzeL+Tg8JdKLp9L/2eELkLeqfaugqLPCkACkcVyZ5oKhUMdiK1WYyLsPzGu44lpCZ0DuXnpZLQ+AVC1EK9JAVfYC8mUCFzaIftT6g2MlaafevpXHQ3T0+CPfoQ58fQE7T6eoQpWYqlkFaV+cjb1n/1+qKCGGqJmSadZt3umADqF3vri46+HKO/BhNOxmAxPwcAdJ89qkvp5N5x7ZKBPm3KAiRNbB0nfiF+DWXMxFy01Ibfuc2Uoclk1h63ML8AgBdAUhqsmK3hI6xTcPA76QWRK9uYqU=
  webhooks:
    secure: EgltABlAcbHR64R6smMyoXOd6sX718RTP7g4YT5SIN5/sOOg16YbkVh585QhrYyYzOBYtliTGgd3pYdLDLotYSaCl+RUKilHmfwDMPKDXYTlNyvqL2Umb3hCOV+HtBTR2LI3DWIZVRjqzE53Mk3OTVTeRpkp9zQuEehNPpbd27O+a33kvFpVvKFjgBRqQgVxxzY4ArZkxZSexQfAxwoqXMpZ5YXLaJ57+0WKuEWekEWB57GQvo5NmwTW5WpmtY89XCu4UlI2p4iyfbuQ1UZqGRJCJDpDKCACFT01tRRVRgiAOVsNU0u2GLdvGnWxsEYSWvGgWgXUk9YQqzi+qjNKqJ5gGLGh4TcFHLOerQxKwDl7PVqVUWN0lv0Es9IonnuJqSEKfpUdBayaDD/ZiQQ5jwVBarcsdkmzitzEaBn9IsNsVpMtAhw5uCjs3v3rR/fSzbTKHUJ9sjINdD6LPtG6Rm5KsmuzNOHXw/F1qf2terBhlxENj/mSEafCwZx1okhnkipkqTvJgCvM5VRLUE3BPE6HEfBJVna9E4qIdPQdw+7kuyovvrdZSpBO76sP5vdlQoJpUqr7xa5BzSwG5vdh+jgKQNfbCiRlRwLwTjsJGHu1YPOiREu/z4FOSqt/lSWPD0nrl2CidmF2m7qt1BgR6mr6TL1/QbZkofeKskQjh3Y=
addons:
  sauce_connect:
    username: ebmdatalab
    access_key:
      secure: MlmeHStJ91/CHGiz2wVo8rOsrBjk181DbQPSV4PYlJQyogDuGQrKy8LIkUZlzaXUhhG+H5jdUyfoBGJXhZCCxjwzf4yibZEYpHWvWGfCwb8g4SFr9doDSxmwY0aJgYkJGAMPKxz7MQ4LXgNp/6z+NO1kw3uU0poNQEMz73Do9rd6iVRvjRThj4q0wGv5AoV3+LshVtHKHBpcEs0ZyHzmEuGrpEuR0Ak4g1Dif0HoMmAepmU/pNui18tMHx3HDtBerKuo1+ou4eEtxBUy4OVnAas7+zgw3e1pWawsf3mMTSKGxY6rFTIE5A5N+Te589vVGucpc0XzfoxpFtn13DLMFG4Mf0mdBgHYBo+fCuIrBwPZ0RoD7NV7RfhKKGQ4rpLP6uwjFTCtbG1CyT5+zz/RxxbE+guqmIUZI6oZZQsXx7mk2cypQgV3La41O85VJ6Y74QRCK9c59ChiDxjfYbIMLysP8E4d5GmLnLUFlGjSTr9G8bP3kHZqhE12tg2JPqhMG3eMvQngQfQhgXqh4shBPOJCUthinafJizyJ9lscx0OMmNkb4GMqXAEJNIz7Xp0xFJvsOnLyoWO3rJ2UoZd1tNuv4OnhQOsZvvHePueAyYateXPHsFPOaIhgoAQkGkALI+E8+2dSWUVZo5EqYd00beM4Ni6GTThpZ3tIIfTu2+w=
after_success:
  - docker-compose run test /bin/bash -c 'pip install coveralls==1.3.0 && cd openprescribing && coveralls'
branches:
  only:
  - master
