---
- name: Setup Virtualenv and upgrade setuptools and pip
  pip:
    name: "{{ item }}"
    state: latest
    virtualenv: "{{ virtualenv_path }}"
  with_items:
    - setuptools
    - pip

- name: install virtualenvwrapper
  pip:
    name: virtualenvwrapper

- name: Create the .virtualenvs directory
  become: yes
  file:
    state: directory
    path: "{{ HOME }}/.virtualenvs"
    owner: "{{ USER }}"
    group: "{{ USER }}"

- name: Connect virtualenvwrapper
  file:
    state: link
    src: "{{ virtualenv_path }}"
    path: "{{ HOME }}/.virtualenvs/openprescribing"
    owner: "{{ USER }}"
    group: "{{ USER }}"

- name: Ensure cd to dir after workon
  lineinfile:
    dest: "{{ HOME }}/.virtualenvs/postactivate"
    line: "cd {{ apps_root }}"
    create: yes

- name: Activate virtualenv on login
  lineinfile:
    dest: "{{ HOME }}/.bashrc"
    line: "workon openprescribing"

- name: Install requirements
  pip:
    virtualenv: "{{ virtualenv_path }}"
    requirements: "{{ requirements_path }}"

- name: Install jshint and less
  become: yes
  npm:
    name: "{{ item }}"
    path: "{{ apps_root }}/media/js"
    global: yes
  with_items:
    - jshint
    - less

- name: Install browserify with version range (for browserify-shim)
  become: yes
  npm:
    name: browserify
    path: "{{ apps_root }}/media/js"
    global: yes
    version: '>= 2.3.0 <4'

- name: Install packages based on package.json
  npm:
    path: "{{ apps_root }}/media/js"

- name: Install ipdb (pinned for python 2.7)
  pip:
    name: ipdb
    virtualenv: "{{ virtualenv_path }}"
    version: 0.10.2

- name: Make manage.py executable
  file:
    path: "{{ apps_root }}/manage.py"
    mode: 0777

- name: Create environment file
  copy:
    remote_src: yes
    src: "{{ repo_root }}/environment-sample"
    dest: "{{ repo_root }}/environment"
    force: yes

- name: Set up environment file
  replace:
    regexp: "{{ item.name }}=.*"
    replace: "{{ item.name }}={{ item.content }}"
    path: "{{ repo_root }}/environment"
  with_items: "{{ envvars }}"

- name: Django migrate
  become: yes
  become_user: "{{ USER }}"
  shell: ". {{ virtualenv_path }}/bin/activate && ./manage.py migrate"
  args:
    chdir: "{{ apps_root }}"
