name: CI

on:
  push:

jobs:
  unit_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Retrieve Google Cloud credentials
        run: ./.github/scripts/decrypt_secret.sh
        env:
          GOOGLE_CLOUD_GITHUB_ACTIONS_PASSPHRASE: ${{ secrets.GOOGLE_CLOUD_GITHUB_ACTIONS_PASSPHRASE }}
      - name: Generate SAUCE_HOST
        run: |
          echo "::set-env name=SAUCE_HOST::$(ip -4 addr show scope global dev docker0 | grep inet | awk '{print $2}' | cut -d / -f 1)"
      - name: Unit tests
        run: docker-compose run --service-ports test && docker-compose run --service-ports test-production
        env:
          TEST_SUITE: nonfunctional

  # Functional tests are failing on Travis too!
  #
  # functional_tests:
  #   runs-on: ubuntu-latest
  #
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #     - name: Retrieve Google Cloud credentials
  #       run: ./.github/scripts/decrypt_secret.sh
  #       env:
  #         GOOGLE_CLOUD_GITHUB_ACTIONS_PASSPHRASE: ${{ secrets.GOOGLE_CLOUD_GITHUB_ACTIONS_PASSPHRASE }}
  #     - name: Generate SAUCE_HOST
  #       run: |
  #         echo "::set-env name=SAUCE_HOST::$(ip -4 addr show scope global dev docker0 | grep inet | awk '{print $2}' | cut -d / -f 1)"
  #     - name: Functional tests
  #       run: docker-compose run --service-ports test && docker-compose run --service-ports test-production
  #       env:
  #         TEST_SUITE: functional
  #         BROWSER: "internet explorer:11.0:Windows 7"

  ansible_buildout_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Ansible buildout test
        run: docker run -v ${GITHUB_WORKSPACE}:/openprescribing/ dockette/stretch /bin/bash -c "cd /openprescribing/ansible && bash test_playbook.sh"
        env:
          LANG: en_US.UTF-8

  linting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'
      - name: "Linting"
        run: |
          pip install black==19.3b0
          pip install flake8==3.7.8
          scripts/lint.sh

  notify_slack:
    runs-on: ubuntu-latest
    needs: [ unit_test , ansible_buildout_test, linting ]

    steps:
      - name: Test
        run: whoami
      - name: Slack notification
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        uses: cemkiy/action-slacker@master
        with:
          # requirements fields for slack
          channel: '#technoise'
          icon_url: 'https://slack-files2.s3-us-west-2.amazonaws.com/avatars/2017-07-20/215209949315_eb7b9d555efd1274773e_512.png'
          username: 'Github Actions - OpenPrescribing'
          # # attachment fields(not required)
          # fallback: 'Required plain-text summary of the attachment.'
          # color: '#36a64f'
          # pretext: 'Optional text that appears above the attachment block'
          # author_name: 'John Doe'
          # author_link: 'http://jdoe.com/me/'
          # author_icon: 'http://imageurl.com/icons/icon.jpg'
          # title: 'Slack API Documentation'
          # title_link: 'https://api.slack.com/'
          # text: 'Optional text that appears within the attachment'
          # image_url: 'http://my-website.com/path/to/image.jpg'
          # thumb_url: 'http://example.com/path/to/thumb.png'
          # footer: 'Slack API'
          # footer_icon: 'https://platform.slack-edge.com/img/default_application_icon.png'
